export enum HttpErrorCode {
	// 4xx Client Errors
	BAD_REQUEST = 'BAD_REQUEST',
	UNAUTHORIZED = 'UNAUTHORIZED',
	FORBIDDEN = 'FORBIDDEN',
	NOT_FOUND = 'NOT_FOUND',
	CONFLICT = 'CONFLICT',
	VALIDATION_FAILED = 'VALIDATION_FAILED',
	// 5xx Server Errors
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
